import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Assignment-1",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="max-w-full mx-auto bg-gray-300 p-4">
          {children}
        </main>
      </body>
    </html>
  );
}

// DEEPER P1

// It does not appear in the URL path at all.
// Route groups allow us to organize our files logically or apply distinct layouts (via an inner (marketing)/layout.tsx)
// to specific routes without altering the public URL structure. For example, app/(marketing)/about/page.tsx still renders at /about.
